// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jopwlswlflkscyxxqjor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcHdsc3dsZmxrc2N5eHhxam9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTk3NjIsImV4cCI6MjA2NzA3NTc2Mn0.fp81jLcEuaXff0qhrBiPfhoYp_b8GhVgNa8aaVFdNXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});